//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM_PROJECT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalScheduleManagementEntities : DbContext
    {
        public HospitalScheduleManagementEntities()
            : base("name=HospitalScheduleManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblAppointment> tblAppointments { get; set; }
        public virtual DbSet<tblDisease> tblDiseases { get; set; }
        public virtual DbSet<tblDiseaseCategory> tblDiseaseCategories { get; set; }
        public virtual DbSet<tblDoctor> tblDoctors { get; set; }
        public virtual DbSet<tblPatient> tblPatients { get; set; }
        public virtual DbSet<tblPatientDisease> tblPatientDiseases { get; set; }
        public virtual DbSet<tblTimeSchedule> tblTimeSchedules { get; set; }
        public virtual DbSet<tblUserDetail> tblUserDetails { get; set; }
    }
}
