//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDoctor()
        {
            this.tblAppointments = new HashSet<tblAppointment>();
        }
    
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string DoorNo { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Specialization { get; set; }
        public string Education { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Schedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointment> tblAppointments { get; set; }
        public virtual tblDiseaseCategory tblDiseaseCategory { get; set; }
        public virtual tblTimeSchedule tblTimeSchedule { get; set; }
    }
}
