//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDisease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDisease()
        {
            this.tblPatientDiseases = new HashSet<tblPatientDisease>();
        }
    
        public int DiseaseId { get; set; }
        public string DiseaseName { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual tblDiseaseCategory tblDiseaseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatientDisease> tblPatientDiseases { get; set; }
    }
}
