//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientDisease
    {
        public int PatientDiseaseId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DiseaseId { get; set; }
    
        public virtual tblDisease tblDisease { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
